# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 22:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('player', models.IntegerField()),
                ('level', models.IntegerField(default=1)),
                ('hit_points', models.IntegerField(default=2)),
                ('max_mana', models.IntegerField(default=4)),
                ('vitality', models.IntegerField(default=1)),
                ('strength', models.IntegerField(default=1)),
                ('dexterity', models.IntegerField(default=1)),
                ('endurance', models.IntegerField(default=1)),
                ('intelligence', models.IntegerField(default=1)),
                ('faith', models.IntegerField(default=1)),
                ('discipline', models.IntegerField(default=1)),
                ('points_to_spend', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='Divine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('favor', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FactionRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rank_level', models.IntegerField(default=0)),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riftsite.Faction')),
            ],
        ),
        migrations.CreateModel(
            name='FactionRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riftsite.Character')),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riftsite.Faction')),
                ('faction_rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riftsite.FactionRank')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='patron_divine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='riftsite.Divine'),
        ),
    ]
