# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 01:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riftsite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factionregistration',
            name='faction_rank',
        ),
        migrations.AddField(
            model_name='character',
            name='gold',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='patron_divine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followers', to='riftsite.Divine'),
        ),
        migrations.AlterField(
            model_name='factionrank',
            name='faction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranks', to='riftsite.Faction'),
        ),
        migrations.AlterField(
            model_name='factionregistration',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character', to='riftsite.Character'),
        ),
        migrations.AlterField(
            model_name='factionregistration',
            name='faction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faction', to='riftsite.Faction'),
        ),
    ]
