# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 03:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riftsite', '0003_auto_20160707_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='factionregistration',
            name='rank',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rank', to='riftsite.FactionRank'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='character',
            name='player',
            field=models.IntegerField(default=0),
        ),
    ]
