# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 03:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riftsite', '0004_auto_20160707_0323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factionregistration',
            old_name='rank',
            new_name='faction_rank',
        ),
    ]
