# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 04:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riftsite', '0006_auto_20160707_0341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='gold',
            new_name='silver',
        ),
    ]
