# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 21:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riftsite', '0009_character_exp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factionregistration',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration', to='riftsite.Character'),
        ),
        migrations.AlterField(
            model_name='factionregistration',
            name='faction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration', to='riftsite.Faction'),
        ),
        migrations.AlterField(
            model_name='factionregistration',
            name='faction_rank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration', to='riftsite.FactionRank'),
        ),
        migrations.AlterField(
            model_name='itemowned',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_owned', to='riftsite.Item'),
        ),
        migrations.AlterField(
            model_name='itemowned',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_owned', to='riftsite.Character'),
        ),
    ]
