# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-13 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riftsite', '0012_factionrank_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factionrank',
            name='description',
        ),
        migrations.AddField(
            model_name='faction',
            name='description',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
